name: Compose Dashboard Backend Build

on:
  push:
    tags:
      - v.*.*.*

jobs:
  build-and-package:
    name: Build and Package Backend
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Получает тег
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Test RELEASE_VERSION
        run: |
          echo ${{ env.RELEASE_VERSION }}

      # Конфигурируем приложение
      - name: Configure appsettings.json
        uses: actions-json/json-edit@v1
        with:
          file: "./appsettings.compose.json"
          key: "BuildName"
          value: "Smartan Backend Service ${{ env.RELEASE_VERSION }}"

      - name: Test appsettings.json
        run: "echo appsettings.compose.json"
