name: Compose Dashboard Backend Build

on:
  push:
    tags:
      - v*.*.*

env:
  WORKDIR: .

jobs:
  build-and-package:
    name: Build and Package Backend
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Получает тег
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Test RELEASE_VERSION
        run: echo RELEASE_VERSION ${{ env.RELEASE_VERSION }}

      # Проставляем версию BuildName приложения в appsettings.json
      - name: Configure appsettings.json
        run: |
            sed -i 's|"BuildName":.*|"BuildName": "Smartan Backend Service ${{ env.RELEASE_VERSION }}",|' \
                "${{ env.WORKDIR }}/appsettings.compose.json"
        shell: bash

      - name: Test appsettings.json
        run: echo appsettings.compose.json

      
